# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Kernel": "00_kernel.ipynb",
         "LinearKernel": "00_kernel.ipynb",
         "PolynomialKernel": "00_kernel.ipynb",
         "HomogeneousPolynomialKernel": "00_kernel.ipynb",
         "GaussianKernel": "00_kernel.ipynb",
         "HyperbolicKernel": "00_kernel.ipynb",
         "PrecomputedKernel": "00_kernel.ipynb",
         "Fuzzifier": "01_fuzzifiers.ipynb",
         "CrispFuzzifier": "01_fuzzifiers.ipynb",
         "LinearFuzzifier": "01_fuzzifiers.ipynb",
         "ExponentialFuzzifier": "01_fuzzifiers.ipynb",
         "QuantileConstantPiecewiseFuzzifier": "01_fuzzifiers.ipynb",
         "QuantileLinearPiecewiseFuzzifier": "01_fuzzifiers.ipynb",
         "logger": "03_mulearn.ipynb",
         "solve_optimization_tensorflow": "02_optimization.ipynb",
         "solve_optimization_gurobi": "02_optimization.ipynb",
         "solve_optimization": "02_optimization.ipynb",
         "FuzzyInductor": "03_mulearn.ipynb"}

modules = ["kernel.py",
           "fuzzifier.py",
           "optimization.py",
           "__init__.py"]

doc_url = "https://dariomalchiodi.github.io/mulearn/"

git_url = "https://github.com/dariomalchiodi/mulearn/tree/master/"

def custom_doc_links(name): return None
